# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.package_info import PackageInfo

class TestPackageInfo(unittest.TestCase):
    """PackageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageInfo:
        """Test PackageInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageInfo`
        """
        model = PackageInfo()
        if include_optional:
            return PackageInfo(
                id = '',
                name = '',
                short_description = '',
                overview = '',
                is_premium = True,
                adult = True,
                rich_desc_url = '',
                thumb_image = '',
                preview_image = '',
                type = '',
                target_filename = '',
                owner = '',
                category = '',
                tile_color = '',
                feature_id = '',
                price = 1.337,
                target_system = 'Server',
                guid = '',
                is_registered = True,
                exp_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                versions = [
                    embyapi.models.package_version_info.PackageVersionInfo(
                        name = '', 
                        guid = '', 
                        version_str = '', 
                        classification = 'Release', 
                        description = '', 
                        required_version_str = '', 
                        source_url = '', 
                        checksum = '', 
                        target_filename = '', 
                        info_url = '', 
                        runtimes = '', 
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                enable_in_app_store = True,
                installs = 56
            )
        else:
            return PackageInfo(
        )
        """

    def testPackageInfo(self):
        """Test PackageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
