# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.user_notification_info import UserNotificationInfo

class TestUserNotificationInfo(unittest.TestCase):
    """UserNotificationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserNotificationInfo:
        """Test UserNotificationInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserNotificationInfo`
        """
        model = UserNotificationInfo()
        if include_optional:
            return UserNotificationInfo(
                notifier_key = '',
                setup_module_url = '',
                service_name = '',
                plugin_id = '',
                friendly_name = '',
                id = '',
                enabled = True,
                user_ids = [
                    ''
                    ],
                device_ids = [
                    ''
                    ],
                library_ids = [
                    ''
                    ],
                event_ids = [
                    ''
                    ],
                user_id = '',
                is_self_notification = True,
                group_items = True,
                options = {
                    'key' : ''
                    }
            )
        else:
            return UserNotificationInfo(
        )
        """

    def testUserNotificationInfo(self):
        """Test UserNotificationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
