# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.image_type import ImageType

class TestImageType(unittest.TestCase):
    """ImageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageType(self):
        """Test ImageType"""
        # inst = ImageType()

if __name__ == '__main__':
    unittest.main()
