# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.user_action import UserAction

class TestUserAction(unittest.TestCase):
    """UserAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAction:
        """Test UserAction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAction`
        """
        model = UserAction()
        if include_optional:
            return UserAction(
                id = '',
                server_id = '',
                user_id = '',
                item_id = '',
                type = 'PlayedItem',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                position_ticks = 56,
                played = True,
                is_favorite = True
            )
        else:
            return UserAction(
        )
        """

    def testUserAction(self):
        """Test UserAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
