# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.music_genres_service_api import MusicGenresServiceApi


class TestMusicGenresServiceApi(unittest.TestCase):
    """MusicGenresServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MusicGenresServiceApi()

    def tearDown(self) -> None:
        pass

    def test_get_musicgenres(self) -> None:
        """Test case for get_musicgenres

        Gets all music genres from a given item, folder, or the entire library
        """
        pass

    def test_get_musicgenres_by_name(self) -> None:
        """Test case for get_musicgenres_by_name

        Gets a music genre, by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
