# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.synced_item_progress import SyncedItemProgress

class TestSyncedItemProgress(unittest.TestCase):
    """SyncedItemProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncedItemProgress:
        """Test SyncedItemProgress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncedItemProgress`
        """
        model = SyncedItemProgress()
        if include_optional:
            return SyncedItemProgress(
                progress = 1.337,
                status = 'Queued'
            )
        else:
            return SyncedItemProgress(
        )
        """

    def testSyncedItemProgress(self):
        """Test SyncedItemProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
