# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.transcode_reason import TranscodeReason

class TestTranscodeReason(unittest.TestCase):
    """TranscodeReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscodeReason(self):
        """Test TranscodeReason"""
        # inst = TranscodeReason()

if __name__ == '__main__':
    unittest.main()
