# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.library_service_api import LibraryServiceApi


class TestLibraryServiceApi(unittest.TestCase):
    """LibraryServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LibraryServiceApi()

    def tearDown(self) -> None:
        pass

    def test_delete_items(self) -> None:
        """Test case for delete_items

        Deletes an item from the library and file system
        """
        pass

    def test_delete_items_by_id(self) -> None:
        """Test case for delete_items_by_id

        Deletes an item from the library and file system
        """
        pass

    def test_get_albums_by_id_similar(self) -> None:
        """Test case for get_albums_by_id_similar

        Finds albums similar to a given album.
        """
        pass

    def test_get_artists_by_id_similar(self) -> None:
        """Test case for get_artists_by_id_similar

        Finds albums similar to a given album.
        """
        pass

    def test_get_games_by_id_similar(self) -> None:
        """Test case for get_games_by_id_similar

        Finds games similar to a given game.
        """
        pass

    def test_get_items_by_id_ancestors(self) -> None:
        """Test case for get_items_by_id_ancestors

        Gets all parents of an item
        """
        pass

    def test_get_items_by_id_criticreviews(self) -> None:
        """Test case for get_items_by_id_criticreviews

        Gets critic reviews for an item
        """
        pass

    def test_get_items_by_id_deleteinfo(self) -> None:
        """Test case for get_items_by_id_deleteinfo

        Gets delete info for an item
        """
        pass

    def test_get_items_by_id_download(self) -> None:
        """Test case for get_items_by_id_download

        Downloads item media
        """
        pass

    def test_get_items_by_id_file(self) -> None:
        """Test case for get_items_by_id_file

        Gets the original file of an item
        """
        pass

    def test_get_items_by_id_similar(self) -> None:
        """Test case for get_items_by_id_similar

        Gets similar items
        """
        pass

    def test_get_items_by_id_thememedia(self) -> None:
        """Test case for get_items_by_id_thememedia

        Gets theme videos and songs for an item
        """
        pass

    def test_get_items_by_id_themesongs(self) -> None:
        """Test case for get_items_by_id_themesongs

        Gets theme songs for an item
        """
        pass

    def test_get_items_by_id_themevideos(self) -> None:
        """Test case for get_items_by_id_themevideos

        Gets theme videos for an item
        """
        pass

    def test_get_items_counts(self) -> None:
        """Test case for get_items_counts

        """
        pass

    def test_get_items_intros(self) -> None:
        """Test case for get_items_intros

        Gets info to debug intros
        """
        pass

    def test_get_libraries_availableoptions(self) -> None:
        """Test case for get_libraries_availableoptions

        """
        pass

    def test_get_library_mediafolders(self) -> None:
        """Test case for get_library_mediafolders

        Gets all user media folders.
        """
        pass

    def test_get_library_physicalpaths(self) -> None:
        """Test case for get_library_physicalpaths

        Gets a list of physical paths from virtual folders
        """
        pass

    def test_get_library_selectablemediafolders(self) -> None:
        """Test case for get_library_selectablemediafolders

        Gets all user media folders.
        """
        pass

    def test_get_movies_by_id_similar(self) -> None:
        """Test case for get_movies_by_id_similar

        Finds movies and trailers similar to a given movie.
        """
        pass

    def test_get_shows_by_id_similar(self) -> None:
        """Test case for get_shows_by_id_similar

        Finds tv shows similar to a given one.
        """
        pass

    def test_get_trailers_by_id_similar(self) -> None:
        """Test case for get_trailers_by_id_similar

        Finds movies and trailers similar to a given trailer.
        """
        pass

    def test_post_items_by_id_delete(self) -> None:
        """Test case for post_items_by_id_delete

        Deletes an item from the library and file system
        """
        pass

    def test_post_items_delete(self) -> None:
        """Test case for post_items_delete

        Deletes an item from the library and file system
        """
        pass

    def test_post_library_media_updated(self) -> None:
        """Test case for post_library_media_updated

        Reports that new movies have been added by an external source
        """
        pass

    def test_post_library_movies_added(self) -> None:
        """Test case for post_library_movies_added

        Deprecated. Use /Library/Media/Updated
        """
        pass

    def test_post_library_movies_updated(self) -> None:
        """Test case for post_library_movies_updated

        Deprecated. Use /Library/Media/Updated
        """
        pass

    def test_post_library_refresh(self) -> None:
        """Test case for post_library_refresh

        Starts a library scan
        """
        pass

    def test_post_library_series_added(self) -> None:
        """Test case for post_library_series_added

        Deprecated. Use /Library/Media/Updated
        """
        pass

    def test_post_library_series_updated(self) -> None:
        """Test case for post_library_series_updated

        Deprecated. Use /Library/Media/Updated
        """
        pass


if __name__ == '__main__':
    unittest.main()
