# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.playback_error_code import PlaybackErrorCode

class TestPlaybackErrorCode(unittest.TestCase):
    """PlaybackErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaybackErrorCode(self):
        """Test PlaybackErrorCode"""
        # inst = PlaybackErrorCode()

if __name__ == '__main__':
    unittest.main()
