# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.api_on_playback_progress import ApiOnPlaybackProgress

class TestApiOnPlaybackProgress(unittest.TestCase):
    """ApiOnPlaybackProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiOnPlaybackProgress:
        """Test ApiOnPlaybackProgress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiOnPlaybackProgress`
        """
        model = ApiOnPlaybackProgress()
        if include_optional:
            return ApiOnPlaybackProgress(
                playlist_index = 56,
                playlist_length = 56,
                event_name = 'TimeUpdate'
            )
        else:
            return ApiOnPlaybackProgress(
        )
        """

    def testApiOnPlaybackProgress(self):
        """Test ApiOnPlaybackProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
