# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.edit_object_container import EditObjectContainer

class TestEditObjectContainer(unittest.TestCase):
    """EditObjectContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditObjectContainer:
        """Test EditObjectContainer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditObjectContainer`
        """
        model = EditObjectContainer()
        if include_optional:
            return EditObjectContainer(
                object = None,
                default_object = None,
                type_name = '',
                editor_root = embyapi.models.editors/editor_root.Editors.EditorRoot(
                    property_conditions = [
                        embyapi.models.conditions/property_condition.Conditions.PropertyCondition(
                            affected_property_id = '', 
                            condition_type = 'Visible', 
                            target_property_id = '', 
                            simple_condition = 'IsTrue', 
                            value_condition = 'IsEqual', 
                            value = embyapi.models.value.Value(), )
                        ], 
                    postback_actions = [
                        embyapi.models.actions/postback_action.Actions.PostbackAction(
                            target_editor_id = '', 
                            postback_command_id = '', 
                            command_parameter_property_id = '', )
                        ], 
                    title_button = embyapi.models.editors/editor_button_item.Editors.EditorButtonItem(
                        editor_type = 'Group', 
                        name = '', 
                        id = '', 
                        allow_empty = True, 
                        is_read_only = True, 
                        is_advanced = True, 
                        display_name = '', 
                        description = '', 
                        feature_requires_premiere = True, 
                        parent_id = '', ), 
                    editor_items = [
                        embyapi.models.editors/editor_base.Editors.EditorBase(
                            name = '', 
                            id = '', 
                            allow_empty = True, 
                            is_read_only = True, 
                            is_advanced = True, 
                            display_name = '', 
                            description = '', 
                            feature_requires_premiere = True, 
                            parent_id = '', )
                        ], 
                    editor_type = 'Group', 
                    name = '', 
                    id = '', 
                    allow_empty = True, 
                    is_read_only = True, 
                    is_advanced = True, 
                    display_name = '', 
                    description = '', 
                    feature_requires_premiere = True, 
                    parent_id = '', )
            )
        else:
            return EditObjectContainer(
        )
        """

    def testEditObjectContainer(self):
        """Test EditObjectContainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
