# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.trailers_service_api import TrailersServiceApi


class TestTrailersServiceApi(unittest.TestCase):
    """TrailersServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrailersServiceApi()

    def tearDown(self) -> None:
        pass

    def test_get_trailers(self) -> None:
        """Test case for get_trailers

        Finds movies and trailers similar to a given trailer.
        """
        pass


if __name__ == '__main__':
    unittest.main()
