# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.subtitle_location_type import SubtitleLocationType

class TestSubtitleLocationType(unittest.TestCase):
    """SubtitleLocationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtitleLocationType(self):
        """Test SubtitleLocationType"""
        # inst = SubtitleLocationType()

if __name__ == '__main__':
    unittest.main()
