# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.video_service_api import VideoServiceApi


class TestVideoServiceApi(unittest.TestCase):
    """VideoServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VideoServiceApi()

    def tearDown(self) -> None:
        pass

    def test_get_videos_by_id_by_streamfilename(self) -> None:
        """Test case for get_videos_by_id_by_streamfilename

        Gets a video stream
        """
        pass

    def test_get_videos_by_id_stream(self) -> None:
        """Test case for get_videos_by_id_stream

        Gets a video stream
        """
        pass

    def test_get_videos_by_id_stream_by_container(self) -> None:
        """Test case for get_videos_by_id_stream_by_container

        Gets a video stream
        """
        pass

    def test_head_videos_by_id_by_streamfilename(self) -> None:
        """Test case for head_videos_by_id_by_streamfilename

        Gets a video stream
        """
        pass

    def test_head_videos_by_id_stream(self) -> None:
        """Test case for head_videos_by_id_stream

        Gets a video stream
        """
        pass

    def test_head_videos_by_id_stream_by_container(self) -> None:
        """Test case for head_videos_by_id_stream_by_container

        Gets a video stream
        """
        pass


if __name__ == '__main__':
    unittest.main()
