# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.ui_command import UICommand

class TestUICommand(unittest.TestCase):
    """UICommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UICommand:
        """Test UICommand
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UICommand`
        """
        model = UICommand()
        if include_optional:
            return UICommand(
                command_type = 'Custom',
                command_id = '',
                is_visible = True,
                is_enabled = True,
                caption = '',
                set_focus = True,
                confirmation_prompt = ''
            )
        else:
            return UICommand(
        )
        """

    def testUICommand(self):
        """Test UICommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
