# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.models.drawing_image_orientation import DrawingImageOrientation

class TestDrawingImageOrientation(unittest.TestCase):
    """DrawingImageOrientation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrawingImageOrientation(self):
        """Test DrawingImageOrientation"""
        # inst = DrawingImageOrientation()

if __name__ == '__main__':
    unittest.main()
