# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.audio_service_api import AudioServiceApi


class TestAudioServiceApi(unittest.TestCase):
    """AudioServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AudioServiceApi()

    def tearDown(self) -> None:
        pass

    def test_get_audio_by_id_by_streamfilename(self) -> None:
        """Test case for get_audio_by_id_by_streamfilename

        Gets an audio stream
        """
        pass

    def test_get_audio_by_id_stream(self) -> None:
        """Test case for get_audio_by_id_stream

        Gets an audio stream
        """
        pass

    def test_get_audio_by_id_stream_by_container(self) -> None:
        """Test case for get_audio_by_id_stream_by_container

        Gets an audio stream
        """
        pass

    def test_head_audio_by_id_by_streamfilename(self) -> None:
        """Test case for head_audio_by_id_by_streamfilename

        Gets an audio stream
        """
        pass

    def test_head_audio_by_id_stream(self) -> None:
        """Test case for head_audio_by_id_stream

        Gets an audio stream
        """
        pass

    def test_head_audio_by_id_stream_by_container(self) -> None:
        """Test case for head_audio_by_id_stream_by_container

        Gets an audio stream
        """
        pass


if __name__ == '__main__':
    unittest.main()
