# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.playstate_service_api import PlaystateServiceApi


class TestPlaystateServiceApi(unittest.TestCase):
    """PlaystateServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlaystateServiceApi()

    def tearDown(self) -> None:
        pass

    def test_delete_users_by_userid_playeditems_by_id(self) -> None:
        """Test case for delete_users_by_userid_playeditems_by_id

        Marks an item as unplayed
        """
        pass

    def test_delete_users_by_userid_playingitems_by_id(self) -> None:
        """Test case for delete_users_by_userid_playingitems_by_id

        Reports that a user has stopped playing an item
        """
        pass

    def test_post_sessions_playing(self) -> None:
        """Test case for post_sessions_playing

        Reports playback has started within a session
        """
        pass

    def test_post_sessions_playing_ping(self) -> None:
        """Test case for post_sessions_playing_ping

        Pings a playback session
        """
        pass

    def test_post_sessions_playing_progress(self) -> None:
        """Test case for post_sessions_playing_progress

        Reports playback progress within a session
        """
        pass

    def test_post_sessions_playing_stopped(self) -> None:
        """Test case for post_sessions_playing_stopped

        Reports playback has stopped within a session
        """
        pass

    def test_post_users_by_userid_items_by_itemid_userdata(self) -> None:
        """Test case for post_users_by_userid_items_by_itemid_userdata

        Updates userdata for an item
        """
        pass

    def test_post_users_by_userid_playeditems_by_id(self) -> None:
        """Test case for post_users_by_userid_playeditems_by_id

        Marks an item as played
        """
        pass

    def test_post_users_by_userid_playeditems_by_id_delete(self) -> None:
        """Test case for post_users_by_userid_playeditems_by_id_delete

        Marks an item as unplayed
        """
        pass

    def test_post_users_by_userid_playingitems_by_id(self) -> None:
        """Test case for post_users_by_userid_playingitems_by_id

        Reports that a user has begun playing an item
        """
        pass

    def test_post_users_by_userid_playingitems_by_id_delete(self) -> None:
        """Test case for post_users_by_userid_playingitems_by_id_delete

        Reports that a user has stopped playing an item
        """
        pass

    def test_post_users_by_userid_playingitems_by_id_progress(self) -> None:
        """Test case for post_users_by_userid_playingitems_by_id_progress

        Reports a user's playback progress
        """
        pass


if __name__ == '__main__':
    unittest.main()
