# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from embyapi.api.environment_service_api import EnvironmentServiceApi


class TestEnvironmentServiceApi(unittest.TestCase):
    """EnvironmentServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnvironmentServiceApi()

    def tearDown(self) -> None:
        pass

    def test_get_environment_defaultdirectorybrowser(self) -> None:
        """Test case for get_environment_defaultdirectorybrowser

        Gets the parent path of a given path
        """
        pass

    def test_get_environment_directorycontents(self) -> None:
        """Test case for get_environment_directorycontents

        Gets the contents of a given directory in the file system
        """
        pass

    def test_get_environment_drives(self) -> None:
        """Test case for get_environment_drives

        Gets available drives from the server's file system
        """
        pass

    def test_get_environment_networkdevices(self) -> None:
        """Test case for get_environment_networkdevices

        Gets a list of devices on the network
        """
        pass

    def test_get_environment_networkshares(self) -> None:
        """Test case for get_environment_networkshares

        Gets shares from a network device
        """
        pass

    def test_get_environment_parentpath(self) -> None:
        """Test case for get_environment_parentpath

        Gets the parent path of a given path
        """
        pass

    def test_post_environment_directorycontents(self) -> None:
        """Test case for post_environment_directorycontents

        Gets the contents of a given directory in the file system
        """
        pass

    def test_post_environment_validatepath(self) -> None:
        """Test case for post_environment_validatepath

        Gets the contents of a given directory in the file system
        """
        pass


if __name__ == '__main__':
    unittest.main()
