# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from embyapi.models.recommendation_dto import RecommendationDto

from embyapi.api_client import ApiClient, RequestSerialized
from embyapi.api_response import ApiResponse
from embyapi.rest import RESTResponseType


class MoviesServiceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_movies_recommendations(
        self,
        category_limit: Annotated[Optional[StrictInt], Field(description="The max number of categories to return")] = None,
        item_limit: Annotated[Optional[StrictInt], Field(description="The max number of items to return per category")] = None,
        user_id: Annotated[Optional[StrictStr], Field(description="Optional. Filter by user id, and attach user data")] = None,
        parent_id: Annotated[Optional[StrictStr], Field(description="Specify this to localize the search to a specific item or folder. Omit to use the root")] = None,
        enable_images: Annotated[Optional[StrictBool], Field(description="Optional, include image information in output")] = None,
        enable_user_data: Annotated[Optional[StrictBool], Field(description="Optional, include user data")] = None,
        image_type_limit: Annotated[Optional[StrictInt], Field(description="Optional, the max number of images to return, per image type")] = None,
        enable_image_types: Annotated[Optional[StrictStr], Field(description="Optional. The image types to include in the output.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[RecommendationDto]:
        """Gets movie recommendations

        Requires authentication as user

        :param category_limit: The max number of categories to return
        :type category_limit: int
        :param item_limit: The max number of items to return per category
        :type item_limit: int
        :param user_id: Optional. Filter by user id, and attach user data
        :type user_id: str
        :param parent_id: Specify this to localize the search to a specific item or folder. Omit to use the root
        :type parent_id: str
        :param enable_images: Optional, include image information in output
        :type enable_images: bool
        :param enable_user_data: Optional, include user data
        :type enable_user_data: bool
        :param image_type_limit: Optional, the max number of images to return, per image type
        :type image_type_limit: int
        :param enable_image_types: Optional. The image types to include in the output.
        :type enable_image_types: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_movies_recommendations_serialize(
            category_limit=category_limit,
            item_limit=item_limit,
            user_id=user_id,
            parent_id=parent_id,
            enable_images=enable_images,
            enable_user_data=enable_user_data,
            image_type_limit=image_type_limit,
            enable_image_types=enable_image_types,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[RecommendationDto]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_movies_recommendations_with_http_info(
        self,
        category_limit: Annotated[Optional[StrictInt], Field(description="The max number of categories to return")] = None,
        item_limit: Annotated[Optional[StrictInt], Field(description="The max number of items to return per category")] = None,
        user_id: Annotated[Optional[StrictStr], Field(description="Optional. Filter by user id, and attach user data")] = None,
        parent_id: Annotated[Optional[StrictStr], Field(description="Specify this to localize the search to a specific item or folder. Omit to use the root")] = None,
        enable_images: Annotated[Optional[StrictBool], Field(description="Optional, include image information in output")] = None,
        enable_user_data: Annotated[Optional[StrictBool], Field(description="Optional, include user data")] = None,
        image_type_limit: Annotated[Optional[StrictInt], Field(description="Optional, the max number of images to return, per image type")] = None,
        enable_image_types: Annotated[Optional[StrictStr], Field(description="Optional. The image types to include in the output.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[RecommendationDto]]:
        """Gets movie recommendations

        Requires authentication as user

        :param category_limit: The max number of categories to return
        :type category_limit: int
        :param item_limit: The max number of items to return per category
        :type item_limit: int
        :param user_id: Optional. Filter by user id, and attach user data
        :type user_id: str
        :param parent_id: Specify this to localize the search to a specific item or folder. Omit to use the root
        :type parent_id: str
        :param enable_images: Optional, include image information in output
        :type enable_images: bool
        :param enable_user_data: Optional, include user data
        :type enable_user_data: bool
        :param image_type_limit: Optional, the max number of images to return, per image type
        :type image_type_limit: int
        :param enable_image_types: Optional. The image types to include in the output.
        :type enable_image_types: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_movies_recommendations_serialize(
            category_limit=category_limit,
            item_limit=item_limit,
            user_id=user_id,
            parent_id=parent_id,
            enable_images=enable_images,
            enable_user_data=enable_user_data,
            image_type_limit=image_type_limit,
            enable_image_types=enable_image_types,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[RecommendationDto]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_movies_recommendations_without_preload_content(
        self,
        category_limit: Annotated[Optional[StrictInt], Field(description="The max number of categories to return")] = None,
        item_limit: Annotated[Optional[StrictInt], Field(description="The max number of items to return per category")] = None,
        user_id: Annotated[Optional[StrictStr], Field(description="Optional. Filter by user id, and attach user data")] = None,
        parent_id: Annotated[Optional[StrictStr], Field(description="Specify this to localize the search to a specific item or folder. Omit to use the root")] = None,
        enable_images: Annotated[Optional[StrictBool], Field(description="Optional, include image information in output")] = None,
        enable_user_data: Annotated[Optional[StrictBool], Field(description="Optional, include user data")] = None,
        image_type_limit: Annotated[Optional[StrictInt], Field(description="Optional, the max number of images to return, per image type")] = None,
        enable_image_types: Annotated[Optional[StrictStr], Field(description="Optional. The image types to include in the output.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Gets movie recommendations

        Requires authentication as user

        :param category_limit: The max number of categories to return
        :type category_limit: int
        :param item_limit: The max number of items to return per category
        :type item_limit: int
        :param user_id: Optional. Filter by user id, and attach user data
        :type user_id: str
        :param parent_id: Specify this to localize the search to a specific item or folder. Omit to use the root
        :type parent_id: str
        :param enable_images: Optional, include image information in output
        :type enable_images: bool
        :param enable_user_data: Optional, include user data
        :type enable_user_data: bool
        :param image_type_limit: Optional, the max number of images to return, per image type
        :type image_type_limit: int
        :param enable_image_types: Optional. The image types to include in the output.
        :type enable_image_types: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_movies_recommendations_serialize(
            category_limit=category_limit,
            item_limit=item_limit,
            user_id=user_id,
            parent_id=parent_id,
            enable_images=enable_images,
            enable_user_data=enable_user_data,
            image_type_limit=image_type_limit,
            enable_image_types=enable_image_types,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[RecommendationDto]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_movies_recommendations_serialize(
        self,
        category_limit,
        item_limit,
        user_id,
        parent_id,
        enable_images,
        enable_user_data,
        image_type_limit,
        enable_image_types,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if category_limit is not None:
            
            _query_params.append(('CategoryLimit', category_limit))
            
        if item_limit is not None:
            
            _query_params.append(('ItemLimit', item_limit))
            
        if user_id is not None:
            
            _query_params.append(('UserId', user_id))
            
        if parent_id is not None:
            
            _query_params.append(('ParentId', parent_id))
            
        if enable_images is not None:
            
            _query_params.append(('EnableImages', enable_images))
            
        if enable_user_data is not None:
            
            _query_params.append(('EnableUserData', enable_user_data))
            
        if image_type_limit is not None:
            
            _query_params.append(('ImageTypeLimit', image_type_limit))
            
        if enable_image_types is not None:
            
            _query_params.append(('EnableImageTypes', enable_image_types))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json', 
                'application/xml'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'apikeyauth', 
            'embyauth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/Movies/Recommendations',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


