# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from embyapi.models.codec_type import CodecType
from embyapi.models.profile_condition import ProfileCondition
from typing import Optional, Set
from typing_extensions import Self

class CodecProfile(BaseModel):
    """
    CodecProfile
    """ # noqa: E501
    type: Optional[CodecType] = Field(default=None, alias="Type")
    conditions: Optional[List[ProfileCondition]] = Field(default=None, alias="Conditions")
    apply_conditions: Optional[List[ProfileCondition]] = Field(default=None, alias="ApplyConditions")
    codec: Optional[StrictStr] = Field(default=None, alias="Codec")
    container: Optional[StrictStr] = Field(default=None, alias="Container")
    __properties: ClassVar[List[str]] = ["Type", "Conditions", "ApplyConditions", "Codec", "Container"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodecProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item in self.conditions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Conditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in apply_conditions (list)
        _items = []
        if self.apply_conditions:
            for _item in self.apply_conditions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ApplyConditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodecProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Type": obj.get("Type"),
            "Conditions": [ProfileCondition.from_dict(_item) for _item in obj["Conditions"]] if obj.get("Conditions") is not None else None,
            "ApplyConditions": [ProfileCondition.from_dict(_item) for _item in obj["ApplyConditions"]] if obj.get("ApplyConditions") is not None else None,
            "Codec": obj.get("Codec"),
            "Container": obj.get("Container")
        })
        return _obj


