# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from embyapi.models.version import Version
from typing import Optional, Set
from typing_extensions import Self

class CommonPluginsIPlugin(BaseModel):
    """
    Interface IPlugin  
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The name of the plugin", alias="Name")
    description: Optional[StrictStr] = Field(default=None, description="The description.", alias="Description")
    id: Optional[StrictStr] = Field(default=None, description="The unique id.", alias="Id")
    version: Optional[Version] = Field(default=None, alias="Version")
    assembly_file_path: Optional[StrictStr] = Field(default=None, description="The path to the assembly file", alias="AssemblyFilePath")
    data_folder_path: Optional[StrictStr] = Field(default=None, description="The full path to the data folder, where the plugin can store any miscellaneous files needed", alias="DataFolderPath")
    __properties: ClassVar[List[str]] = ["Name", "Description", "Id", "Version", "AssemblyFilePath", "DataFolderPath"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommonPluginsIPlugin from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['Version'] = self.version.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommonPluginsIPlugin from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Name": obj.get("Name"),
            "Description": obj.get("Description"),
            "Id": obj.get("Id"),
            "Version": Version.from_dict(obj["Version"]) if obj.get("Version") is not None else None,
            "AssemblyFilePath": obj.get("AssemblyFilePath"),
            "DataFolderPath": obj.get("DataFolderPath")
        })
        return _obj


