# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from embyapi.models.package_version_class import PackageVersionClass
from typing import Optional, Set
from typing_extensions import Self

class InstallationInfo(BaseModel):
    """
    Class InstallationInfo  
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The id.", alias="Id")
    name: Optional[StrictStr] = Field(default=None, description="The name.", alias="Name")
    assembly_guid: Optional[StrictStr] = Field(default=None, description="The assembly guid.", alias="AssemblyGuid")
    version: Optional[StrictStr] = Field(default=None, description="The version.", alias="Version")
    update_class: Optional[PackageVersionClass] = Field(default=None, alias="UpdateClass")
    percent_complete: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The percent complete.", alias="PercentComplete")
    __properties: ClassVar[List[str]] = ["Id", "Name", "AssemblyGuid", "Version", "UpdateClass", "PercentComplete"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstallationInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if percent_complete (nullable) is None
        # and model_fields_set contains the field
        if self.percent_complete is None and "percent_complete" in self.model_fields_set:
            _dict['PercentComplete'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstallationInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "Name": obj.get("Name"),
            "AssemblyGuid": obj.get("AssemblyGuid"),
            "Version": obj.get("Version"),
            "UpdateClass": obj.get("UpdateClass"),
            "PercentComplete": obj.get("PercentComplete")
        })
        return _obj


