# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OperatingSystem(str, Enum):
    """
    OperatingSystem
    """

    """
    allowed enum values
    """
    WINDOWS = 'Windows'
    LINUX = 'Linux'
    OSX = 'OSX'
    BSD = 'BSD'
    ANDROID = 'Android'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperatingSystem from a JSON string"""
        return cls(json.loads(json_str))


