# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SyncJobOption(str, Enum):
    """
    SyncJobOption
    """

    """
    allowed enum values
    """
    NAME = 'Name'
    QUALITY = 'Quality'
    UNWATCHEDONLY = 'UnwatchedOnly'
    SYNCNEWCONTENT = 'SyncNewContent'
    ITEMLIMIT = 'ItemLimit'
    PROFILE = 'Profile'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SyncJobOption from a JSON string"""
        return cls(json.loads(json_str))


