# coding: utf-8

"""
    Emby Server REST API

    Explore the Emby Server API

    The version of the OpenAPI document: 4.8.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from embyapi.models.base_item_dto import BaseItemDto
from embyapi.models.item_file_info import ItemFileInfo
from typing import Optional, Set
from typing_extensions import Self

class SyncedItem(BaseModel):
    """
    SyncedItem
    """ # noqa: E501
    server_id: Optional[StrictStr] = Field(default=None, alias="ServerId")
    sync_job_id: Optional[StrictInt] = Field(default=None, alias="SyncJobId")
    sync_job_name: Optional[StrictStr] = Field(default=None, alias="SyncJobName")
    sync_job_date_created: Optional[datetime] = Field(default=None, alias="SyncJobDateCreated")
    sync_job_item_id: Optional[StrictInt] = Field(default=None, alias="SyncJobItemId")
    original_file_name: Optional[StrictStr] = Field(default=None, alias="OriginalFileName")
    item: Optional[BaseItemDto] = Field(default=None, alias="Item")
    user_id: Optional[StrictStr] = Field(default=None, alias="UserId")
    additional_files: Optional[List[ItemFileInfo]] = Field(default=None, alias="AdditionalFiles")
    __properties: ClassVar[List[str]] = ["ServerId", "SyncJobId", "SyncJobName", "SyncJobDateCreated", "SyncJobItemId", "OriginalFileName", "Item", "UserId", "AdditionalFiles"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SyncedItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of item
        if self.item:
            _dict['Item'] = self.item.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in additional_files (list)
        _items = []
        if self.additional_files:
            for _item in self.additional_files:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AdditionalFiles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SyncedItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ServerId": obj.get("ServerId"),
            "SyncJobId": obj.get("SyncJobId"),
            "SyncJobName": obj.get("SyncJobName"),
            "SyncJobDateCreated": obj.get("SyncJobDateCreated"),
            "SyncJobItemId": obj.get("SyncJobItemId"),
            "OriginalFileName": obj.get("OriginalFileName"),
            "Item": BaseItemDto.from_dict(obj["Item"]) if obj.get("Item") is not None else None,
            "UserId": obj.get("UserId"),
            "AdditionalFiles": [ItemFileInfo.from_dict(_item) for _item in obj["AdditionalFiles"]] if obj.get("AdditionalFiles") is not None else None
        })
        return _obj


